config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/auth/:provider/callback' => 'sessions#oauth_login'

  get '/hazelnuts' => 'coffees#hazelnut'

  get '/vanilla' => 'coffees#vanilla'

  get '/banana' => 'coffees#vanilla'

  resources :reviews
  resources :coffees do 
    resources :reviews, only: [:new, :index]
  end 


  resources :brands
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
        has_many :coffees
        validates :name, presence: true, uniqueness: true 

        scope :alpha, -> { order(:name) }
    
end 

app/models/coffee.rb
class Coffee < ApplicationRecord
    belongs_to :brand
    belongs_to :user #creator of it 
    has_many :reviews 
    has_many :users, through: :reviews

    # accepts_nested_attributes_for :brand 

    validates :flavor, presence: true
    validate :not_a_duplicate

    scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}

    def self.hazelnut
       Coffee.all.select do |coffee| 
        coffee.flavor.include?('Hazelnut')
       end 
    end 

    def self.vanilla 
       Coffee.all.select do |coffee| 
        coffee.flavor.downcase.include?('vanilla')
    end 
  end

    def self.alpha
        order(:flavor)
    end

    
    def brand_attributes=(attributes)
        brand = Brand.find_or_create_by(attributes) if !attributes['name'].empty? 
    end 

    def not_a_duplicate
    # if there is already a coffee with that flavor && brand, throw an error

    if Coffee.find_by(flavor: flavor, brand_id: brand_id)
        errors.add(:flavor, 'Has already been added for that brand')
        end
    end


  def flavor_and_brand
    "#{flavor} - #{brand.name}"
  end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user 
    belongs_to :coffee 

    validates :title, presence: true
    validates :stars, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 6}

    validates :coffee, uniqueness: { scope: :user, message: "has already been reviewed by you" }

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews 
    has_many :reviewed_coffees, through: :reviews, source: :coffee 

    has_many :coffees 

    has_secure_password 

    validates :username, :email, presence: true 
    validates :username, uniqueness: true



def self.from_omniauth(auth)

    where(email: auth.info.email).first_or_initialize do |user|
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private 

    def logged_in?
        !!session[:user_id]
    end 

    def current_user 
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end 

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in? 
    end 

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

    def index 
        @brands = Brand.alpha 
    end 
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new 
        @coffee = Coffee.new 
        @coffee.build_brand 
    end 

    def create 
        @coffee = Coffee.new(coffee_params)
        @coffee.user_id = current_user.id 
     
        if @coffee.save 
            redirect_to coffee_path(@coffee)
        else 
            @coffee.build_brand 
            render :new 
    end 
end 

def index 
    @title = "All"
    @coffees = Coffee.order_by_rating.includes(:brand)
end 

def show 
    @coffee = Coffee.find_by_id(params[:id])
end 


def edit 
end 

def hazelnut
    # @coffees = Coffee.all.select do |coffee| 
    #     coffee.flavor.include?('Hazelnut')
    # binding.pry
    @title = "Hazelnut"
    @coffees = Coffee.hazelnut 
    render :index
end 

def vanilla 
    @coffees = Coffee.vanilla 
    @title = "Vanilla"
    render :index
end 

def update 
    if @coffee.update(coffee_params)
        redirect_to coffee_path(@coffee)
    else 
        render :edit 
    end 
end 

    private 

    def coffee_params 
        params.require(:coffee).permit(:flavor, :description, :brand_id, brand_attributes: [:name])
    end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :redirect_if_not_logged_in 

def new
    if @coffee = Coffee.find_by_id(params[:coffee_id])
      @review = @coffee.reviews.build
    else
      @review = Review.new
    end
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
  end

  def index
    if @coffee = Coffee.find_by_id(params[:coffee_id])
      #nested
      @reviews = @coffee.reviews
    else
      #it's not nested
      @reviews = Review.all
    end
  end

  private

  def review_params
      params.require(:review).permit(:coffee_id, :content, :stars, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
     

    def index 
    end 

    def new 
        
    end 

     def create
    
     @user = User.find_by(username: params[:user][:username])

     #if we find something & they have the right password
     if @user && @user.authenticate(params[:user][:password])
       session[:user_id] = @user.id
       redirect_to user_path(@user.id)
     else
        flash[:message] = "Sorry, please try again"
        redirect_to login_path
     end
  end

def oauth_login
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

    def destroy 
        session.clear 
        redirect_to root_path 
    end 

    private 

    def auth
        request.env['omniauth.auth']
    end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new 
    end 

   def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else
            render :new 
        end 
    end 

    def show 
    
        @user = User.find_by(id:params[:id])
        redirect_to '/' if !@user 
    end 



    private 

    def user_params 
        params.require(:user).permit(:username, :email, :password)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
def display_header(review)
    if params[:coffee_id]
        content_tag(:h1, "Add a Review for #{review.coffee.flavor} -  #{review.coffee.brand.name}")
    else
      content_tag(:h1, "Create a review")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/index.html.erb
<h1>All the Brands</h1>

    <ol>
        <% @brands.each do |brand| %>
            <li><%= brand.name%></li>

            <% end %>
    <ol>

app/views/coffees/_form.html.erb
<%= render partial: 'errors', locals: {object: @coffee}  %>
<% form_for(@coffee) do |f|%>
  <div>
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <br>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <br>

  <p> Select a Brand that already exists: </p>
  <div>
    <%= f.collection_select :brand_id, Brand.all, :id, :name, include_blank: 'Select One'%>

  </div>

  <p> Or create a new Brand: </p>
  <div>
    <%=f.fields_for :brand do |b| %>
      <%= b.label :name %>
      <%= b.text_field :name %>
    <% end %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/coffees/hazelnut.html.erb
<h1> Hazelnut </h1>

    <% @coffees.each do |coffee| %>
            <li><%= coffee.flavor %></li>

            <% end %>

app/views/coffees/index.html.erb
<h1><%= @title %> Coffees</h1>

<% @coffees.each do |c| %>

    <h2><%= c.flavor%> - <%= c.brand.name %></h2>
    <%= link_to "Write a review", new_coffee_review_path(c.id)%>
    <div>
        <p><%= c.description%></p>
    </div>
<% end %>

app/views/coffees/new.html.erb
<h1> Make a new Coffee </h1>

<%= render partial: 'layouts/errors', locals: {object: @coffee}  %>

<%= form_for(@coffee) do |f| %>
<div>
<%= f.label :flavor %>
<%= f.text_field :flavor %>
</div>
<div>
<%= f.label :description %>
<%= f.text_field :description %>
</div>

<p> Select a brand that already exists: </p>
    <div>
        <%= f.collection_select :brand_id, Brand.all, :id, :name, include_blank: 'Select One' %>
    
    </div>

<p> Or create a new Brand: </p>
    <div>
    <%= f.fields_for :brand do |b| %>
        <%= b.label :name %>
        <%= b.text_field :name %>
    <% end %>
    </div>
    <br>
    <%= f.submit %>
<% end %>

app/views/coffees/show.html.erb
<h1><%= @coffee.flavor%></h1>

<h2><%= @coffee.flavor%> - <%= @coffee.brand.name %></h2>
<div>
    <p><%= @coffee.description %></p>
</div>

app/views/coffees/vanilla.html.erb
<h1> Here are all of the Vanilla flavors </h1>

    <% @coffees.each do |coffee| %>
            <li><%= coffee.flavor %></li>

            <% end %>

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeReviewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<div>
<div class ='container'>
<%= link_to "Log Out", logout_path, method: :delete%>
<%= link_to "Add a Coffee", new_coffee_path %>
<%= link_to "All Coffees", coffees_path %>
<%= link_to "Add a Review", new_review_path%> 
<%= link_to "All Reviews", reviews_path%> 
<%= link_to "All Brands", brands_path %>
  </div>
   <div class ='container'>
    <p class="h1 display-12">Find Your Perfect Coffee Cup!</p>
    <div class ='container'>
</div>


  <body>
  
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<% if @coffee %>
  <h1>Reviews for <%= @coffee.flavor%> - <%= @coffee.brand.name%></h1>
<% else %>
  <h1>All the Reviews </h1>
<% end %>

    <ul>
        <% @reviews.each do |r| %>
        <li><%= r.coffee.flavor%>: <%= link_to r.title, review_path(r)%> - <%= r.stars%></li> <br>
    <%end%>
    </ul>

app/views/reviews/new.html.erb
<%= display_header(@review)%>

<%= render partial: 'layouts/errors', locals: {object: @review} %>

<%= form_for(@review) do |f|%>
  <% if params[:coffee_id] %>
    <%= f.hidden_field :coffee_id %>
  <% else %>
    <div>
      <%= f.label :coffee_id, "Select a Coffee" %>
      <%= f.collection_select :coffee_id, Coffee.alpha,:id, :flavor_and_brand, include_blank: true %>
    </div>
  <% end %>
  <div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:0, max:5 %>
  </div>
  <br>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content, size: "25x10" %>
  </div>
  <br>



  <%= f.submit %>

<% end %>

app/views/reviews/show.html.erb
<h1><%= @review.title%> - <%= @review.stars %></h1>

<p><%= @review.content%></p>

app/views/users/new.html.erb
<h1> Sign up here! </h1>

<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= form_for(:user) do |f| %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

    <%= f.submit "Sign Up"%>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%=@user.username%></h1>